---
all:
  hosts:
    node1:
      ansible_host: hp124.utah.cloudlab.us
    node2:
      ansible_host: hp142.utah.cloudlab.us
    node3:
      ansible_host: hp131.utah.cloudlab.us
    node4:
      ansible_host: hp123.utah.cloudlab.us
    node5:
      ansible_host: hp132.utah.cloudlab.us
    node6:
      ansible_host: hp154.utah.cloudlab.us
    node7:
      ansible_host: hp143.utah.cloudlab.us
    node8:
      ansible_host: hp149.utah.cloudlab.us
  children:
    server:
      hosts:
        node1:
    clients:
      hosts:
        node2:
        node3:
        node4:
        node5:
        node6:
        node7:
        node8:
  vars:
    ansible_user: pierg
    ansible_ssh_private_key_file: /Users/pierluigigrossi/cloudlab.key