---
all:
  hosts:
    node0:
      ansible_host: hp197.utah.cloudlab.us
    node1:
      ansible_host: hp192.utah.cloudlab.us
    node2:
      ansible_host: hp161.utah.cloudlab.us
    node3:
      ansible_host: hp168.utah.cloudlab.us
    node4:
      ansible_host: hp185.utah.cloudlab.us
    node5:
      ansible_host: hp186.utah.cloudlab.us
    node6:
      ansible_host: hp164.utah.cloudlab.us
    node7:
      ansible_host: hp191.utah.cloudlab.us
    node8:
      ansible_host: hp189.utah.cloudlab.us
    node9:
      ansible_host: hp171.utah.cloudlab.us
  vars:
    ansible_user: LoreCMYK
    ansible_ssh_private_key_file: /home/lorenzo/.ssh/SSH_Key_Cloudlab
