---
- name: eTran full node setup
  import_playbook: 01-system-prep.yml
- import_playbook: 02-clone-sources.yml
- import_playbook: 03-build-kernel.yml
- import_playbook: 04-reboot.yml
- import_playbook: 05-install-eTran.yml
